project:
  type: website
  output-dir: docs

# Meta
description-meta: "Personal Website: Alonso Ogueda-Oliva"
author-meta: "Alonso Ogueda-Oliva"

website:
  title: "Alonso Ogueda-Oliva"
  image: "https://quarto.org/quarto.png"
  description: "Personal Website: Alonso Ogueda-Oliva"

  navbar:
    background: light

    left:
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          - text: News
            href: posts.qmd#category=news
          - text: Events
            href: posts.qmd#category=event
          - text: Contact
            href: contact.qmd
      - text: Research
        menu:
          - text: Research Areas
            href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Outreach
        menu:
        - text: Presentations
          href: posts.qmd#category=presentation

    right:
      - text: CV
        href: "files/CV - Alonso Ogueda Oliva.pdf"
      - icon: github
        href: https://github.com/aoguedao
        target: _blank
  page-navigation: true

  page-footer:
    left: "[Alonso Ogueda-Oliva](http://www.github.com/aoguedao) &copy; <script>document.write(new Date().getFullYear())</script>"
    right:
      - icon: github
        href: https://github.com/aoguedao
        target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: true

  draft-mode: unlinked

  repo-url: https://github.com/aoguedao/aoguedao.github.io
#  repo-actions: [edit, issue, source]

  open-graph: true

  twitter-card: false
#  card-style: summary

  site-url: "https://aoguedao.github.io"

  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/aoguedao\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

execute:
  freeze: auto